### ISSUE TITLE
install.sh doesn't check for python3 versions 10+

### ISSUE THREAD

**Issue by redragerover** [lyrebird-voice-changer/lyrebird#100]
https://github.com/lyrebird-voice-changer/lyrebird/blob/eaa755872da64f96dbe7dabcc38b90fe7e771876/install.sh#L41
    
 will return python "3.1" and trigger invalid python version for python versions 3.10 and above.

**Comment by ssieb** [comment]
Why do you think that?  The `+` takes as many digits as it can.
```
# python3 --version | grep -Po '3.\d+'
3.10
```

**Comment by harrego** [comment]
The `install.sh` script in branch main is working, but the latest packaged release (v1.1.0) still holds the old version which doesn't recognize < Python 3.10, that may be why you're experiencing this issue.

I'll create a new release to fix this.

And thanks for issue number 100 :)
