### ISSUE TITLE
Lyrebird has no effect on chromebook/chrome os

### ISSUE THREAD

**Issue by Splatube** [lyrebird-voice-changer/lyrebird#103]
I recently downloaded Lyrebird on my chromebook (crostini) but lyrebird has no effect whatsoever, any idea what is causing this?

**Comment by zombieprocess** [comment]
@Splatube How have you launched it? Does it give you errors?

**Comment by harrego** [comment]
Lyrebird is not supported on Crostini or ChromeOS I'm afraid.
