### ISSUE TITLE
Make it a pythkn package, that can be built into a wheel and installed with pip

### ISSUE THREAD

**Issue by KOLANICH** [lyrebird-voice-changer/lyrebird#104]

**Comment by harrego** [comment]
As a GTK application I'm not sure that a Python package is the best bundling route.

**Comment by KOLANICH** [comment]
`meld` is also a GTK application, but it [provides a package](https://gitlab.gnome.org/GNOME/meld/-/blob/main/setup.py).

**Comment by harrego** [comment]
That's true and I apologize! I'm still reluctant only because the project eventually plans to move away from Python and I don't want to leave users on the hook who would install through this method.

**Comment by KOLANICH** [comment]
>That's true and I apologize!

There is no need to apologize for that :)
