### ISSUE TITLE
Issue in installation 

### ISSUE THREAD

**Issue by MohitR1999** [lyrebird-voice-changer/lyrebird#122]
While trying to install from source by running the file `install.sh`, I'm getting an error that Lyrebird requires python 3.7 or higher, even though I have python 3.11 installed. Seems like a small mistake in the regex that is used to check python version. Instead of the string '3\.\d' which checks for only one digit after the period (.), it should be like this: '3\.\d+', this would check one or more digits, that will fix the issue. However, it would be better to use some other tool like 'cut' to more reliably get the python version

Hope I'm clear :)

**Comment by MohitR1999** [comment]
I'm facing this issue on Manjaro. Here's the system info
![image](https://github.com/lyrebird-voice-changer/lyrebird/assets/31106144/d2061b87-fda4-4658-ac22-60366c2b7845)

**Comment by harrego** [comment]
Yes this has been fixed! Will be included in v1.2.0 releasing in a day or two.

Have you managed to install Lyrebird in the meantime? As you said a quick install.sh patch should work.

**Comment by MohitR1999** [comment]
Yes, I just changed the regex in the script and it worked 🤟

**Comment by harrego** [comment]
Awesome :sunglasses:

**Comment by harrego** [comment]
And this has now been [officially released!](https://github.com/lyrebird-voice-changer/lyrebird/releases/tag/v1.2.0)
