### ISSUE TITLE
No sound

### ISSUE THREAD

**Issue by Shocoo** [lyrebird-voice-changer/lyrebird#135]
So first, there is a virtual device called "Remapped Lyrebird-Output.monitor source" created instead of Lyrebird Virtual Input, i don't know if that is normal. I correctly put my mic as the input device for lb, but the virtual one(Remapped Lyrebird-Output.monitor source), which is the only one created, doesn't make any sound. I'm on EndeavourOS.

**Comment by ayazgv** [comment]
Same on Ubuntu 23.04

**Comment by Xarvex** [comment]
Same on Fedora 38, no error logs and no warnings when launching from the command line.

**Comment by nsauk** [comment]
Here is my data of such `remapped` device:
```
wpctl inspect 83
id 83, type PipeWire:Interface:Node
    adapt.follower.spa-node = ""
    audio.adapt.follower = ""
    audio.channels = "2"
    audio.position = "[ FL, FR ]"
  * client.id = "138"
    clock.quantum-limit = "8192"
    device.class = "filter"
  * factory.id = "6"
    factory.mode = "split"
    library.name = "audioconvert/libspa-audioconvert"
  * media.class = "Audio/Source"
    media.name = "Remapped Lyrebird-Output.monitor source output"
    node.autoconnect = "true"
  * node.description = "Remapped Lyrebird-Output.monitor source"
    node.group = "remap-source-536870913"
    node.link-group = "loopback-1926-12"
  * node.name = "Lyrebird-Input"
    node.trigger = "true"
    node.virtual = "true"
    node.want-driver = "true"
    object.register = "false"
  * object.serial = "1091"
    pulse.module.id = "536870913"
    resample.disable = "true"
    resample.prefill = "true"
    stream.is-live = "true"
```

**Comment by nsauk** [comment]
Realized that I have no sound only for half of presets (including the "Off" option). And then I found a reason — this is a `None` value responsible for `volume_boost` in each of default presets. So for me the issue is solved by such a change in app/core/presets.py:
```diff
 DEFAULT_PRESETS = [
-    Preset("Man", -1.5, None, None),
-    Preset("Woman", 2.5, None, None),
-    Preset("Boy", 1.25, None, None),
-    Preset("Girl", 2.8, None, None),
-    Preset("Darth Vader", -6.0, None, None),
-    Preset("Chipmunk", 10.0, None, None),
+    Preset("Man", -1.5, None, 0),
+    Preset("Woman", 2.5, None, 0),
+    Preset("Boy", 1.25, None, 0),
+    Preset("Girl", 2.8, None, 0),
+    Preset("Darth Vader", -6.0, None, 0),
+    Preset("Chipmunk", 10.0, None, 0),
     Preset("Bad Mic", None, 8, 0),
     Preset("Radio", None, 6, 0),
     Preset("Megaphone", None, 2, 0),
-    Preset("Off", 0.0, None, None)
+    Preset("Off", 0.0, None, 0)
 ]
```

@Shocoo @ayazgv @Xarvex could you please check if this works for you?

**Comment by Scorpiontracks** [comment]
Same issue on Pop!_OS 22.04

**Comment by Shocoo** [comment]
> Realized that I have no sound only for half of presets (including the "Off" option). And then I found a reason — this is a `None` value responsible for `volume_boost` in each of default presets. So for me the issue is solved by such a change in app/core/presets.py:
> ```diff
>  DEFAULT_PRESETS = [
> -    Preset("Man", -1.5, None, None),
> -    Preset("Woman", 2.5, None, None),
> -    Preset("Boy", 1.25, None, None),
> -    Preset("Girl", 2.8, None, None),
> -    Preset("Darth Vader", -6.0, None, None),
> -    Preset("Chipmunk", 10.0, None, None),
> +    Preset("Man", -1.5, None, 0),
> +    Preset("Woman", 2.5, None, 0),
> +    Preset("Boy", 1.25, None, 0),
> +    Preset("Girl", 2.8, None, 0),
> +    Preset("Darth Vader", -6.0, None, 0),
> +    Preset("Chipmunk", 10.0, None, 0),
>      Preset("Bad Mic", None, 8, 0),
>      Preset("Radio", None, 6, 0),
>      Preset("Megaphone", None, 2, 0),
> -    Preset("Off", 0.0, None, None)
> +    Preset("Off", 0.0, None, 0)
>  ]
> ```
> 
> @Shocoo @ayazgv @Xarvex could you please check if this works for you?

Thanks it seems to work well for me !

**Comment by ayazgv** [comment]
@nsauk yeah it works on ubuntu 23.04, Thanks a lot!
