### ISSUE TITLE
No module named 'gi'

### ISSUE THREAD

**Issue by ViktorianoCZ** [lyrebird-voice-changer/lyrebird#48]
I'm on Linux Mint 20,
everything was ok, but when i tried to open lyrebird I got:
raceback (most recent call last):
  File "/usr/share/lyrebird/app.py", line 2, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'

python --version is 3.8.5
Any ideas what may be the problem?

**Comment by ssieb** [comment]
I don't know what the exact naming for for .deb distros is, but look for a package called something like `python3-gobject`.
Or look for what provides `/usr/lib64/python3.8/site-packages/gi/__init__.py`

**Comment by harrego** [comment]
Hey everyone, this issue is similar to #13 in that `gi` needs some additional setup in Linux Mint. Please could you try the steps at https://github.com/aben20807/blog-post/issues/80 and let me know how it goes?

**Comment by abi-aryan** [comment]
I am using Ubuntu 18.04 and the linked solution doesn't work for me. Here's the error:

```
Traceback (most recent call last):
  File "app.py", line 2, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'
```

**Comment by RingOfGyges** [comment]
I am having the same problem as abi-aryan on Ubuntu 20.04.
