### ISSUE TITLE
python problem

### ISSUE THREAD

**Issue by ALtaDoodler** [lyrebird-voice-changer/lyrebird#59]
tried usin the debian install but it wasn't working, so i tried the .tar.gz install, but it's showin pthon problems
![image](https://user-images.githubusercontent.com/64117835/107070770-5c439900-67a9-11eb-8834-bbdf08fcde8c.png)
it was originally on the default 2.7, but i found a way to change it, even then it ain't workin. i'm using zorin os 15.3

**Comment by harrego** [comment]
I tried with bash and had no issues on Python 3.7.5. I think its shell related, could you run `echo $SHELL` and post it here?
