### ISSUE TITLE
Raspberry Pi

### ISSUE THREAD

**Issue by slashtechno** [lyrebird-voice-changer/lyrebird#61]
Can you please port this to Raspberry Pi? There are no voice changers for Raspberry Pi and I would love to use this tool on my Pi.
Also Lyrebird does not create a virtual input device. I am using normal Raspberry Pi OS.

**Comment by harrego** [comment]
Have you tried installing it? I have never tried running Lyrebird on arm although I see no reason it wouldn't. It looks as if Python, GTK, SoX and Pulse are supported on Rasbian.

Let me know how it goes, if you run into any issues be sure to update us, I'd be more than happy to try and get it running.

**Comment by slashtechno** [comment]
I get this while trying to run it. I cloned the repository and executed the install script.
![lyrebirdError](https://user-images.githubusercontent.com/77907286/109398135-649e7800-7900-11eb-84ff-88ba4c21e573.png)

**Comment by harrego** [comment]
Could you try running `sudo apt install libsox-fmt-pulse` and trying again? It is most likely in the Rasbian repos but not 100% sure.

**Comment by slashtechno** [comment]
It is already installed

**Comment by harrego** [comment]
As a sanity test could you try running `pacmd load-module module-null-sink sink_name=Lyrebird-Output` and pasting the output to check why the Pulse sinks aren't being created. My apologies for the tedious debugging, arm is new ground for Lyrebird!

**Comment by slashtechno** [comment]
I entered in the command. What do I do now? (sorry I am not very advanced at Linux)

**Comment by harrego** [comment]
No problem :-) Did you see any output or did it run fine?

**Comment by slashtechno** [comment]
I still get
```
Module module-null-sink not loaded.
Module module-remap-source not loaded.

```

**Comment by harrego** [comment]
The "not loaded" messages are normal and display mostly every time, the errors are these lines:
```
sox FAIL formats: can't open output file `Lyrebird-Output': can not open audio device: No such entity
sox FAIL formats: can't open output file `Lyrebird-Output': can not open audio device: No such entity
```
The two lines mean that PulseAudio couldn't create the virtual audio devices that Lyrebird use to output audio to apps like Discord. There may be a different implementation on the Pi than normal Linux which is causing this.

I have an Raspberry Pi and will take a look a little later at whats happening. I'll let you know when I figure it out!

**Comment by slashtechno** [comment]
> I have an Raspberry Pi and will take a look a little later at whats happening. I'll let you know when I figure it out!

Thank you! I can't wait to use Lyrebird on my Pi :)

**Comment by slashtechno** [comment]
@harrego Any progress?

**Comment by harrego** [comment]
@slashtechno I just tested on the latest version of Pi OS Buster (2021-02-11) and didn't have any issues. I'm really not sure what is happening in this case, I'm really sorry about this.

For anyone who would like to debug this issue further I recommend using [QEMU with this configuration](https://github.com/dhruvvyas90/qemu-rpi-kernel). In the examples listed to run the emulation drop the `-net` argument as QEMU will configure a network manually with no issue.

**Comment by slashtechno** [comment]
So it works?

**Comment by harrego** [comment]
@slashtechno My apologies for the wait! Believing myself from a year ago, it seems I got it working!? There isn't a reason it shouldn't work.

**Comment by harrego** [comment]
I can reopen if you're still having issues with this.
