### ISSUE TITLE
support for pipewire?

### ISSUE THREAD

**Issue by ghost** [lyrebird-voice-changer/lyrebird#62]
please add support for pipewire or pipewire-pulse so fedora users can also change voices

**Comment by harrego** [comment]
Pipewire support is not currently planned but you bring up an interesting point, you mention that Pipewire would bring support for GNOME Wayland users. Does this mean that Pulseaudio is currently not supported on GNOME Wayland? I haven't tried Wayland yet because I'm on Nvidia.

If Pipewire is required for Wayland I may look into it.

**Comment by ssieb** [comment]
Pulseaudio works on Wayland, it has nothing to do with the graphical interface at all.  Also, pipewire emulates pulseaudio, so native support for it is only nice to have, not required.

**Comment by harrego** [comment]
@ssieb Thanks for the info, that's what I suspected but couldn't be fully sure.

I'm not at all opposed to Pipewire support but it's not a priority at the moment, especially when the new C rewrite (563698b) is so tightly integrated with Pulse. Perhaps when the C rewrite is at a good place I'll take a look.

**Comment by ChrisJAllan** [comment]
It can be made to work, at least with a little fiddling, just by replacing `pacmd` with `pactl`, or making a `pacmd` script to just send everything to `pactl`. Pipewire-pulse doesn't support module-remap-source, so it might take some manual remapping to get the correct inputs and outputs.

**Comment by SimpliFly03** [comment]
@ChrisJAllan Just symlinking `pactl` to `pacmd` and manually connecting Lyrebird stuff using Catia makes it work on Pipewire.

**Comment by m0rphtail** [comment]
@SimpliFly03 what do you exactly mean by "connecting Lyrebird stuff using Catia"?

**Comment by Taza53** [comment]
It is no longer working on fedora x11 and wayland both as fedora by default is pipewire now

**Comment by petertrr** [comment]
@Monobastian , fisrt `sudo ln -s /usr/bin/pacmd /usr/bin/pactl`, then you can start lyrebird, select a preset and lyrebird's inputs and outputs should appear in JACK patchbay app (like Catia or QJackCtl or any other). Now, you should be able to hear lyrebird's output through default output device and be able to route it from patchbay into the desired application's input.

**Comment by rashidi77** [comment]
Many of the latest common distros are pushing PipeWire..

**Comment by Relected** [comment]
@rashidi77 that's why I was asking for that, also I will he changing the title so I dont mislead people

**Comment by SoulEst** [comment]
> @Monobastian , fisrt `sudo ln -s /usr/bin/pacmd /usr/bin/pactl`, then you can start lyrebird, select a preset and lyrebird's inputs and outputs should appear in JACK patchbay app (like Catia or QJackCtl or any other). Now, you should be able to hear lyrebird's output through default output device and be able to route it from patchbay into the desired application's input.

That command would to be `sudo ln -s /usr/bin/pactl /usr/bin/pacmd` as pactl would be the target and pacmd would be the link.

**Comment by EsmailELBoBDev2** [comment]
https://github.com/lyrebird-voice-changer/lyrebird/issues/62#issuecomment-974742084 worked for me thx

**Comment by harrego** [comment]
# [Lyrebird now supports PipeWire!](https://github.com/lyrebird-voice-changer/lyrebird/releases/tag/v1.2.0)

If anyone needs additional support please open a new issue.
