### ISSUE TITLE
lyrebird not launching on Ubuntu mate 

### ISSUE THREAD

**Issue by 4GAP3** [lyrebird-voice-changer/lyrebird#72]
I tried installing lyrebird on my Ubuntu mate 20.04 and so far I get this error

```
Traceback (most recent call last):
  File "app.py", line 5, in <module>
    import app.mainwindow as mainwindow
  File "/home/guten/.local/share/lyrebird/app/mainwindow.py", line 10, in <module>
    import app.core.presets as presets
  File "/home/guten/.local/share/lyrebird/app/core/presets.py", line 1, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'

```

I've installed all the dependencies and it still gives me this error. What gives?

**Comment by harrego** [comment]
Have you installed `python3-toml`? And did you install via the installer script or the deb package in releases?

**Comment by 4GAP3** [comment]
I know I'm a little late but it worked this time. Thank you for the help

**Comment by 4GAP3** [comment]
Altho I have closed this issue this app still doesn't change my voice. It stays the same for me, I expect a solution to come sooner or later
