### ISSUE TITLE
Add the app in void linux's repo

### ISSUE THREAD

**Issue by Relected** [lyrebird-voice-changer/lyrebird#78]
I am a void-linux user, and I would love your app to be added to the void linux repo, can you make a request for it?

**Comment by harrego** [comment]
Lyrebird isn't in any official repos at the moment because of the high requirements and connections needed. Last time we checked the project was a lot smaller, so maybe this could change in the future, if we ever re-consider I'll take a look at Void :)

Also s/o schlatt
