### ISSUE TITLE
Turning off = all devices fail

### ISSUE THREAD

**Issue by AbitTheGray** [lyrebird-voice-changer/lyrebird#81]
Running on Debian Sid with kernel 5.7.0-3
Turning the app off requires me to restart pulseaudio otherwise all devices go missing.
```
systemctl --user restart pulseaudio.service
```

After it, I also need to restart Discord as it plays sound effects but not recognize any device.

**Comment by harrego** [comment]
Known issue and fixed in off-branch commit 58aa113, I'll be merging in to `main` soon. Thanks for reporting.
