### ISSUE TITLE
Lauching lyrebird stops pulseeffects from applying its filters

### ISSUE THREAD

**Issue by Corrupt-Specturion** [lyrebird-voice-changer/lyrebird#82]
As soon as I launch lyrebird, pulseeffects stops filtering the audio and blasts overly loud sound in my ears if sound happens to be playing. Don't really know anything about proper issue formatting, sorry. Not sure why this is happening.

**Comment by Arkapravo-Ghosh** [comment]
I've also had this issue. To solve it, simply type in terminal `killall pulseeffects` and then relaunch it. Do this after you've configured Lyrebird for use. That'll solve the problem. Do not close Lyrebird or pulseeffects. To stop lyrebird, the best way is to restart apps which use audio and also `killall pulseeffects` and relaunch. Hope it helps.
