### ISSUE TITLE
(Linux Mint) Package installer listing dependencies I have

### ISSUE THREAD

**Issue by CreativeGrey** [lyrebird-voice-changer/lyrebird#84]
When attempting to install the .deb package, the installer tells me I require a python version of 3.7 or above. I currently have multiple versions of python installed, 2.7, 3.6, 3.7, and 3.9. The latter 2 installed while attempting to fix this.
The exact wording is "Error: Dependency is not satisfiable: python3 (>=3.7.0)"

As far as I can tell, the package reader and Lyrebird are just checking the python3 version, which returns 3.6, even though higher versions are installed. I can't figure out  how to remove 3.6 without breaking my OS either.

The .zip version also doesn't run the install.sh script or the lyrebird script, but I assume these problems are connected.

**Comment by subash017** [comment]
HI, Im Subash
First 
   :Navigate to Control Panel.
   :Click “Uninstall a program”, and a list of all the currently installed programs will display.
   :Select the Python version that you want to uninstall, then click the “Uninstall” button above the list – this has to be done for 
    every Python version installed on the system.
*NOTE: Do not uninstall Python 2.7 interpreter

**Comment by CreativeGrey** [comment]
I'm currently using linux mint, 2.7 and 3.6 are both listed as necessary for the OS to function, so I can't remove those 2. Any other ideas for making it use the proper Python version.

I also don't have a control panel and list of installed programs on linux mint, all i have is the synaptic package manager, which is what tells me that 2.7 and 3.6 are necessary.

**Comment by harrego** [comment]
Is this still an issue for those on Linux Mint? I can take a closer look if needed.

**Comment by CreativeGrey** [comment]
Just installed the latest .deb package, it seems like its working.

**Comment by harrego** [comment]
@CreativeGrey thanks for the update
