### ISSUE TITLE
Broken on Pipewire in Ubuntu

### ISSUE THREAD

**Issue by ryleu** [lyrebird-voice-changer/lyrebird#86]
It's very, VERY broken in pipe. Sometimes it works, most of the time it doesn't. I tried configuring it in helvum, but it only worked when I also pointed my normal mic into discord at the same time, which made weird overlapping and delays. Let me know if you need help testing on pipe, because I'm absolutely willing. 

If I disable other things (like noisetorch), it seems to work okay, but based on my testing, the way it applies sound effects is inherently broken. It *should* expose a virtual input that you can select in your chat app and allow you to select a mic to input from in lyrebird. That way you can configure it to chain multiple things together.

![image](https://user-images.githubusercontent.com/69326171/133121704-65fdab3f-8f28-41af-b624-9067025bda20.png)
Whatever this is does not seem right to me.

This is how other programs do it:
![image](https://user-images.githubusercontent.com/69326171/133121900-13281d17-f6ae-48e0-a3c5-a214338655a0.png)
Input selection (I chose the mic built into my laptop) and then I selected the NoiseTorch mic in Discord as the input and it all hooked up automagically. 

I will say though, in pulse, it works great. Pipewire will be the default in ubuntu rather far down the line, but it will happen eventually, so if you want to continue supporting ubuntu, you should look into it.

**Comment by seangenabe** [comment]
It doesn't run for me at all because it's looking for `pacmd`.

**Comment by harrego** [comment]
Lyrebird works for me out of the box on Ubuntu 22.04 as it ships with both `pactl` and `pacmd`. I agree that this won't be the case for much longer though and Pipewire compatibility is currently being worked on.
