### ISSUE TITLE
No sound from Lyrebird Virtual Input on Manjaro laptop

### ISSUE THREAD

**Issue by BackMountainDevil** [lyrebird-voice-changer/lyrebird#87]
## Waht happen?

No sound from Lyrebird Virtual Input. But internal microphone does get voice input(sliderbar value change as speaking). The input value form Lyrebird alway keeps 0.

## Steps to reproduce

1. Install Lyrebird form Manjaro pamac in AUR
2. Open Lyrebird, toggle the button to turn it on, choose a preset.
3. choose Lyrebird Virtual Input
4. Open Audacity to record, got nothing
5. change input back to internal microphone, got my voice

## Machine Environment

- Lyrebird 1.1.0-2
- pavucontrol 1:5.0-1
- Audacity 2.4.1
- System Kernel: 5.13.15-1-MANJARO x86_64 bits: 64 
- Desktop: KDE Plasma 5.22.5 Distro: Manjaro Linux 21.1.3 Pahvo
- Machine Type: Laptop System: LENOVO v: Lenovo XiaoXinPro-13ARE 2020

Info got from `$ inxi -F`, `$ screenfetch` and pamac

**Comment by harrego** [comment]
Could you open pavucontrol and make sure that while Lyrebird is open and enabled, "SoX" under the Recording tab has the correct microphone selected.

**Comment by BackMountainDevil** [comment]
I test again and it work now. I just say to my mic and the result get uout from the speaker. Thanks for reply
