### ISSUE TITLE
Lyrebird does not recognize python 3.7

### ISSUE THREAD

**Issue by nickzodia** [lyrebird-voice-changer/lyrebird#89]
Hello, everyone.
As shown below, when attempting to install Lyrebird, it returns the message "Lyrebird requires Python version 3.7 or higher", although clearly python 3.7 is installed. 

EDITS: 1. My system info: Fedora 35
2. I just noticed someone had the same problem as me, at [issue 59](https://github.com/lyrebird-voice-changer/lyrebird/issues/59), but didn't follow up in their issue and, therefore, couldn't come to a public solution. 

![image](https://user-images.githubusercontent.com/92753509/145343598-0dfcd880-2e68-49e0-8a7f-80e0ddef3b86.png)

**Comment by harrego** [comment]
Merged
