### ISSUE TITLE
Does not work on linux mint and neither on manjaro

### ISSUE THREAD

**Issue by Cerzino** [lyrebird-voice-changer/lyrebird#95]
Hello for some reason lyrebird stopped working a few days ago on my manjaro gnome machine then i remembered that it used to work on linux mint so i installed that but it only worked for a day there too so now it doesn't do anything at all mo sound nothing did everything that was told in the readme nothing, so i'm probably going to look for another voice changer if there are others for linux.

**Comment by CartoonSitty** [comment]
updated Python 3.6.9 to 3.7.5, and it crashed my GUI - unfortunately looks as though the dependencies aren't compatible with mint so I'm thinking maybe use a virtual machine with the correct dependencies worlking with the OS - any idea which linux version I should try?

**Comment by userATgithubDOTcom** [comment]
Manjaro user here—app doesn't launch, no PID, nothing. Thanks.

**Comment by harrego** [comment]
Hey everyone, could you please run Lyrebird through the terminal (will launch with `lyrebird`) and see if any error messages appear?

**Comment by LuciusOfLegend** [comment]
I ran the lyrebid command and got this error.  Manjaro btw.

Traceback (most recent call last):
  File "/usr/share/lyrebird/app.py", line 13, in <module>
    win = mainwindow.MainWindow()
  File "/usr/share/lyrebird/app/mainwindow.py", line 62, in __init__
    utils.unload_pa_modules(check_state=False)
  File "/usr/share/lyrebird/app/core/utils.py", line 60, in unload_pa_modules
    subprocess.call('pacmd unload-module module-null-sink'.split(" "))
  File "/usr/lib/python3.10/subprocess.py", line 345, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.10/subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1842, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'pacmd'

**Comment by williamd1k0** [comment]
Same here.
The `pacmd` program is provided by Pulse, if it doesn't exist you are probably using Pipewire.

**Comment by LuciusOfLegend** [comment]
I see.  I suppose lyrebird does not support Pipewire yet?

**Comment by williamd1k0** [comment]
Related: #62

**Comment by harrego** [comment]
Thanks @williamd1k0 - merging with #62
