### ISSUE TITLE
failed to load module 

### ISSUE THREAD

**Issue by freddii** [lyrebird-voice-changer/lyrebird#96]
when starting from command line:

Module module-remap-source not loaded.
Module module-null-sink not loaded.

So i had to run first:
pactl load-module module-null-sink
pactl load-module module-remap-source

to load them.

or simply change it in lyrebird itself:
sed -i 's/pacmd/pactl/g' /usr/share/lyrebird/app/core/utils.py

**Comment by harrego** [comment]
Hi freddii, these messages are expected as Lyrebird unloads any existing sinks to avoid creating infinite duplicates.

**Comment by harrego** [comment]
Appears to be a common theme on some distros as mentioned in #34, this is possibly Pipewire related and will keep open until compatibility is stable.

**Comment by harrego** [comment]
Most likely fixed in #111 which will be included in v1.1.1
