### ISSUE TITLE
config file name

### ISSUE THREAD

**Issue by OrionRandD** [lyrebird-voice-changer/lyrebird#99]
For some apps on some distros (like Ubuntu) changing the input won't work. To fix this you need to create a file at ~/.alsoftrc and add the following contents:

Do you mean ".alsoftrc" or ".alsaftrc"?

Is this app still maintained?

**Comment by harrego** [comment]
Hey @OrionRandD - `.alsoftrc` is the correct filename, here's a [sample file](https://github.com/kcat/openal-soft/blob/master/alsoftrc.sample) you can look at.

As mentioned in the README it's recommended you add the following to it if `pavucontrol` has locked the input:
```
drivers = alsa,pulse,core,oss

[pulse]
allow-moves=yes
```

**Comment by OrionRandD** [comment]
> Hey @OrionRandD - `.alsoftrc` is the correct filename, here's a [sample file](https://github.com/kcat/openal-soft/blob/master/alsoftrc.sample) you can look at.
> 
> As mentioned in the README it's recommended you add the following to it if `pavucontrol` has locked the input:
> 
> ```
> drivers = alsa,pulse,core,oss
> 
> [pulse]
> allow-moves=yes
> ```

Thx for the answer.
Is there a possibility for you to record a small video showing how to efficiently use your app?
It appears in the pavucontrol options with sox and, e.g. vokoscreenNG or simplescreennrecorder, in the input sink and output sink as well, but I am really confused on how to choose the correct options in all of them...

**Comment by harrego** [comment]
Under the "Recording" tab in `pavucontrol`, just switch an application to use the input device "Lyrebird Virtual Input". Apps like Discord will also allow you to pick this manually in the Voice settings.
